services:
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    networks:
      - iot-net
    depends_on:
      - modbus-sim
      - mqtt-broker

  modbus-sim:
    build: ./simulator
    command: python server.py
    ports:
      - "1502:1502"
    networks:
      - iot-net

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - iot-net
      
  bridge:
    build: ./bridge
    container_name: bridge
    depends_on:
      - mqtt-broker
      - kafka
    environment:
      MQTT_BROKER: "mqtt://mqtt-broker:1883"
      KAFKA_BROKER: "kafka:29092"
    restart: unless-stopped
    networks:
      - iot-net
      
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      CLUSTER_ID: "0XqLIVmMSfOdA3_zVu5Z9Q"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
    
volumes:
  nodered-data:
  kafka_data:
