services:
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered-data:/data
    networks:
      - iot-net
    depends_on:
      - modbus-sim
      - mqtt-broker

  modbus-sim:
    build: ./simulator
    command: python server.py
    ports:
      - "1502:1502"
    networks:
      - iot-net

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
    
volumes:
  nodered-data:
